# Generated by Django 4.0.5 on 2022-10-01 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0001_initial'),
        ('driver', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('van', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('driver_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.drivers')),
                ('guide_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('van_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van.vandetail')),
            ],
        ),
    ]
