# Generated by Django 4.0.5 on 2022-10-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('guide', '0001_initial'),
        ('variations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='driver_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.drivers'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='guide_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.guide'),
        ),
    ]
